### ISSUE TITLE
Error while creating KITTI submission

### ISSUE THREAD

**Issue by starsong98** [XiaoyuShi97/FlowFormerPlusPlus#10]
Hello, Thank you for releasing your codebase.

I have been trying to create a kitti test set submission, but the following error is occuring:

```
Traceback (most recent call last):
  File "/home/User/anaconda3/envs/flowformerpp/lib/python3.7/site-packages/PIL/Image.py", line 3080, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3), '<f4')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "evaluate_FlowFormer_tile.py", line 525, in <module>
    exp_func(model=model.module, output_path=save_path)
  File "/home/User/anaconda3/envs/flowformerpp/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "evaluate_FlowFormer_tile.py", line 190, in create_kitti_submission
    imageio.imwrite(f'vis_kitti_3patch/image/{test_id}_0.png', image1[0].cpu().permute(1, 2, 0).numpy())
  File "/home/User/anaconda3/envs/flowformerpp/lib/python3.7/site-packages/imageio/v2.py", line 397, in imwrite
    return file.write(im, **kwargs)
  File "/home/User/anaconda3/envs/flowformerpp/lib/python3.7/site-packages/imageio/plugins/pillow.py", line 416, in write
    pil_frame = Image.fromarray(frame, mode=mode)
  File "/home/User/anaconda3/envs/flowformerpp/lib/python3.7/site-packages/PIL/Image.py", line 3083, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 3), <f4
```

From what I looked up, this seems to be happening due to data types.

I am currently using imageio 2.31.2 & pillow 9.4.0.

How can I fix this? Is this due to package versions?

Thank you.

**Comment by XiaoyuShi97** [comment]
https://stackoverflow.com/questions/60138697/typeerror-cannot-handle-this-data-type-1-1-3-f4
Please refer to this solution. astype(np.uint8) should work.
